"""empty message

Revision ID: 97a285507eae
Revises: 
Create Date: 2023-02-24 13:18:36.217666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97a285507eae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_username',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('admin_pwd',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('comment_userid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('comment_topicid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('topic_userid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('topic_status',
               existing_type=mysql.ENUM('1', '0'),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('topic_status',
               existing_type=mysql.ENUM('1', '0'),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('topic_userid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('comment_topicid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('comment_userid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_pwd',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('admin_username',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               nullable=False)

    # ### end Alembic commands ###
